
development:
  adapter: mysql2
  encoding: utf8
  database: project
  pool: 5
  timeout: 5000
  password: "1234"
  host: localhost



test:
   adapter: mysql2
   encoding: utf8
   database: project
   pool: 5
   timeout: 5000
   password: "1234"
   host: localhost


production:
   adapter: mysql2
   encoding: utf8
   database: project
   pool: 5
   timeout: 5000
   password: "1234"
   host: localhost


