
development:
  adapter: mysql2
  encoding: utf8
  database: railsdb
  pool: 5
  timeout: 5000
  username: railsuser
  password: railspass
  host: localhost



test:
   adapter: mysql2
   encoding: utf8
   database: railsdb
   pool: 5
   timeout: 5000
   username: railsuser
   password: railspass
   host: localhost


production:
   adapter: mysql2
   encoding: utf8
   database: railsdb
   pool: 5
   timeout: 5000
   username: railsuser
   password: railspass
   host: localhost


